// Sticky Navigation Bar Functionality
class StickyNav {
  constructor() {
      this.nav = document.getElementById('stickyNav');
          this.hamburger = document.querySelector('.hamburger');
              this.mobileMenu = document.querySelector('.nav-menu-mobile');
                  this.init();
                    }

                      init() {
                          if (!this.nav) return;

                              // Add scroll event listener for sticky effect
                                  window.addEventListener('scroll', () => this.handleScroll());

                                      // Mobile menu toggle
                                          if (this.hamburger) {
                                                this.hamburger.addEventListener('click', () => this.toggleMobileMenu());
                                                    }

                                                        // Close mobile menu on link click
                                                            const mobileLinks = document.querySelectorAll('.nav-menu-mobile a');
                                                                mobileLinks.forEach(link => {
                                                                      link.addEventListener('click', () => this.closeMobileMenu());
                                                                          });

                                                                              // Set active link based on current page
                                                                                  this.setActiveLink();

                                                                                      // Close mobile menu on outside click
                                                                                          document.addEventListener('click', (e) => this.handleOutsideClick(e));
                                                                                            }

                                                                                              handleScroll() {
                                                                                                  if (window.scrollY > 10) {
                                                                                                        this.nav.classList.add('scrolled');
                                                                                                            } else {
                                                                                                                  this.nav.classList.remove('scrolled');
                                                                                                                      }
                                                                                                                        }

                                                                                                                          toggleMobileMenu() {
                                                                                                                              if (!this.mobileMenu) return;

                                                                                                                                  const isActive = this.mobileMenu.classList.contains('active');
                                                                                                                                      if (isActive) {
                                                                                                                                            this.closeMobileMenu();
                                                                                                                                                } else {
                                                                                                                                                      this.openMobileMenu();
                                                                                                                                                          }
                                                                                                                                                            }

                                                                                                                                                              openMobileMenu() {
                                                                                                                                                                  if (this.mobileMenu) {
                                                                                                                                                                        this.mobileMenu.classList.add('active');
                                                                                                                                                                            }
                                                                                                                                                                                if (this.hamburger) {
                                                                                                                                                                                      this.hamburger.classList.add('active');
                                                                                                                                                                                            this.hamburger.setAttribute('aria-expanded', 'true');
                                                                                                                                                                                                }
                                                                                                                                                                                                  }

                                                                                                                                                                                                    closeMobileMenu() {
                                                                                                                                                                                                        if (this.mobileMenu) {
                                                                                                                                                                                                              this.mobileMenu.classList.remove('active');
                                                                                                                                                                                                                  }
                                                                                                                                                                                                                      if (this.hamburger) {
                                                                                                                                                                                                                            this.hamburger.classList.remove('active');
                                                                                                                                                                                                                                  this.hamburger.setAttribute('aria-expanded', 'false');
                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                          handleOutsideClick(e) {
                                                                                                                                                                                                                                              if (this.mobileMenu && !this.mobileMenu.contains(e.target) && 
                                                                                                                                                                                                                                                      this.hamburger && !this.hamburger.contains(e.target)) {
                                                                                                                                                                                                                                                            this.closeMobileMenu();
                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                    setActiveLink() {
                                                                                                                                                                                                                                                                        const currentPath = window.location.pathname;
                                                                                                                                                                                                                                                                            const navLinks = document.querySelectorAll('.nav-link, .nav-menu-mobile a');

                                                                                                                                                                                                                                                                                navLinks.forEach(link => {
                                                                                                                                                                                                                                                                                      const href = link.getAttribute('href');
                                                                                                                                                                                                                                                                                            if (href === currentPath || 
                                                                                                                                                                                                                                                                                                      (currentPath === '/' && href === '/') ||
                                                                                                                                                                                                                                                                                                                (currentPath.includes(href) && href !== '/')) {
                                                                                                                                                                                                                                                                                                                        link.classList.add('active');
                                                                                                                                                                                                                                                                                                                                link.setAttribute('aria-current', 'page');
                                                                                                                                                                                                                                                                                                                                      } else {
                                                                                                                                                                                                                                                                                                                                              link.classList.remove('active');
                                                                                                                                                                                                                                                                                                                                                      link.removeAttribute('aria-current');
                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                    // Performance optimization: Debounce scroll event
                                                                                                                                                                                                                                                                                                                                                                      debounce(func, wait) {
                                                                                                                                                                                                                                                                                                                                                                          let timeout;
                                                                                                                                                                                                                                                                                                                                                                              return function executedFunction(...args) {
                                                                                                                                                                                                                                                                                                                                                                                    const later = () => {
                                                                                                                                                                                                                                                                                                                                                                                            clearTimeout(timeout);
                                                                                                                                                                                                                                                                                                                                                                                                    func(...args);
                                                                                                                                                                                                                                                                                                                                                                                                          };
                                                                                                                                                                                                                                                                                                                                                                                                                clearTimeout(timeout);
                                                                                                                                                                                                                                                                                                                                                                                                                      timeout = setTimeout(later, wait);
                                                                                                                                                                                                                                                                                                                                                                                                                          };
                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                            // Initialize sticky nav when DOM is ready
                                                                                                                                                                                                                                                                                                                                                                                                                            if (document.readyState === 'loading') {
                                                                                                                                                                                                                                                                                                                                                                                                                              document.addEventListener('DOMContentLoaded', () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                  new StickyNav();
                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                      new StickyNav();
                                                                                                                                                                                                                                                                                                                                                                                                                                      }